name: 🐛 Bug Report
description: Reportar um problema ou erro
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar este bug! Por favor, preencha as informações abaixo.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Problema
      description: Uma descrição clara e concisa do problema
      placeholder: Descreva o que aconteceu...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Passos para Reproduzir
      description: Passos detalhados para reproduzir o problema
      placeholder: |
        1. Execute o comando '...'
        2. Configure '...'
        3. Observe o erro '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que você esperava que acontecesse
      placeholder: Descreva o comportamento esperado...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Sistema Operacional
      description: Em qual sistema operacional o problema ocorreu?
      options:
        - Windows Server 2019
        - Windows Server 2022
        - Windows 10
        - Windows 11
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Debian 11
        - Debian 12
        - CentOS 7
        - CentOS 8
        - RHEL 8
        - RHEL 9
        - SUSE Enterprise
        - Outro (especifique nos detalhes)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Informações sobre seu ambiente
      placeholder: |
        - Versão do Azure Arc Agent: [ex. 1.34.0]
        - Região do Azure: [ex. East US]
        - Tipo de conectividade: [Public/Proxy/Private Endpoint]
        - PowerShell/Bash version: [ex. 5.1/4.4]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Erros
      description: Cole logs relevantes, mensagens de erro ou screenshots
      placeholder: |
        ```
        Cole logs aqui...
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer informação adicional que possa ajudar
      placeholder: Contexto adicional, tentativas de solução, etc.
    validations:
      required: false
